---
common__certbot__post_hook: null
common__certbot__pre_hook: null

common__iptables__drop_by_default: true

postgresql_backups_dir: '/var/lib/postgresql/backups/12/main'

postgresql_global_config_options:
  - option: listen_addresses
    value: '*'
