---
- name: Load, enable and [re]start systemd service
  systemd:
    name: '{{ matrix__synapse__service }}'
    daemon_reload: true
    enabled: true
    state: restarted

- name: Restart Nginx
  systemd:
    name: nginx
    state: restarted
