---
- name: Restart Nginx
  systemd:
    name: nginx
    state: restarted

- name: Load, enable and restart Matrix Synapse
  systemd:
    name: '{{ matrix__synapse__service }}'
    daemon_reload: true
    enabled: true
    state: restarted
