---
- name: Create Matrix directories
  file:
    state: directory
    path: '{{ item }}'
    mode: 'u=rwx,g=rwx,o=rx'
    owner: root
    group: root
  with_items:
    - '{{ matrix__conf_dir }}'
    - '{{ matrix__opt_dir }}'
    - '{{ matrix__lib_dir }}'
    - '{{ matrix__log_dir }}'
    - '{{ matrix__run_dir }}'
