---
- name: Install system package
  apt:
    name: nginx

- name: Disable Nginx access log
  lineinfile:
    path: '/etc/nginx/nginx.conf'
    regexp: '^(\s*)#?\s*access_log\s+\S+\s*;\s*$'
    line: '\1#access_log /var/log/nginx/access.log;'
    backrefs: true

- name: Disable Nginx error log
  lineinfile:
    path: '/etc/nginx/nginx.conf'
    regexp: '^(\s*)#?\s*error_log\s+\S+\s*;\s*$'
    line: '\1#error_log /var/log/nginx/error.log;'
    backrefs: true

- name: Install Nginx log config
  copy:
    src: 'files/nginx/syslog.conf'
    dest: '/etc/nginx/conf.d/syslog.conf'
    mode: 'u=rw,g=r,o=r'
    owner: root
    group: root
  notify: Restart Nginx

- name: Create Nginx server configuration
  template:
    src: '../templates/nginx/matrix.conf'
    dest: '/etc/nginx/sites-available/matrix.conf'
    mode: 'u=rw,g=rw,o=r'
    owner: root
    group: root
  notify: Restart Nginx

- name: Enable Nginx server configuration
  file:
    state: link
    src: '/etc/nginx/sites-available/matrix.conf'
    dest: '/etc/nginx/sites-enabled/matrix.conf'
    owner: root
    group: root
  notify: Restart Nginx
