---
- name: Install system package
  apt:
    name: nginx

- name: Install Nginx log config
  copy:
    src: 'files/nginx/syslog.conf'
    dest: '/etc/nginx/conf.d/syslog.conf'
    mode: 'u=rw,g=r,o=r'
    owner: root
    group: root
  notify: Restart Nginx

- name: Create Nginx server configuration
  template:
    src: '../templates/nginx/matrix.conf'
    dest: '/etc/nginx/sites-available/matrix.conf'
    mode: 'u=rw,g=rw,o=r'
    owner: root
    group: root
  notify: Restart Nginx

- name: Enable Nginx server configuration
  file:
    state: link
    src: '/etc/nginx/sites-available/matrix.conf'
    dest: '/etc/nginx/sites-enabled/matrix.conf'
    owner: root
    group: root
  notify: Restart Nginx
