---
- name: Install system packages for Matrix Static
  apt:
    name: golang
  notify: Load, enable and restart Matrix Static

- name: Create Matrix Static system group
  group:
    name: '{{ matrix__static__group }}'
    system: true
  notify: Load, enable and restart Matrix Static

- name: Create Matrix Static system user
  user:
    name: '{{ matrix__static__user }}'
    group: '{{ matrix__static__group }}'
    system: true
    create_home: false
  notify: Load, enable and restart Matrix Static

- name: Create Matrix Static directories
  file:
    state: directory
    path: '{{ item }}'
    mode: 'u=rwx,g=rwx,o=rx'
    owner: '{{ matrix__static__user }}'
    group: '{{ matrix__static__group }}'
  with_items:
    - '{{ matrix__static__conf_dir }}'
    - '{{ matrix__static__opt_dir }}'
    - '{{ matrix__static__src_dir }}'
    - '{{ matrix__static__bin_dir }}'
  notify: Load, enable and restart Matrix Static

- name: Create Matrix Static config
  template:
    src: '../templates/static/config.json'
    dest: '{{ matrix__static__conf_file }}'
    mode: 'u=rw,g=rw,o='
    owner: '{{ matrix__static__user }}'
    group: '{{ matrix__static__group }}'
  notify: Load, enable and restart Matrix Static

- name: Create Matrix Static systemd service
  template:
    src: '../templates/static/matrix-static.service'
    dest: '{{ matrix__static__service_file }}'
    mode: 'u=rw,g=rw,o=r'
    owner: root
    group: root
  notify: Load, enable and restart Matrix Static

- name: Get Matrix Static source code
  get_url:
    url: '{{ matrix__static__url }}'
    checksum: '{{ matrix__static__checksum }}'
    dest: '{{ matrix__static__archive_file }}'
    mode: 'u=rw,g=rw,o=r'
    owner: '{{ matrix__static__user }}'
    group: '{{ matrix__static__group }}'

- name: Extract Matrix Static source code
  become_user: '{{ matrix__static__user }}'
  unarchive:
    remote_src: true
    src: '{{ matrix__static__archive_file }}'
    dest: '{{ matrix__static__src_dir }}'
    creates: '{{ matrix__static__src_dir }}/README.md'
    extra_opts:
      - '--strip-components=1'
  notify: Load, enable and restart Matrix Static
