---
- copy:
    src: files/yggdrasil.list
    dest: /etc/apt/sources.list.d/yggdrasil.list
    owner: root
    group: root
    mode: u=rw,g=r,o=r
- apt:
    update_cache: true
    name: yggdrasil
    state: present
- template:
    src: templates/yggdrasil.conf
    dest: /etc/yggdrasil.conf
    owner: root
    group: root
    mode: u=rw,g=,o=
  notify:
    - Enable and reload Yggdrasil service
