---
- name: Restart Nginx
  systemd:
    name: nginx
    state: restarted

- name: Load, enable and restart FediHub Website
  systemd:
    name: '{{ fedihub__website__service }}'
    daemon_reload: true
    enabled: true
    state: restarted
