#!/usr/bin/env ruby
# frozen_string_literal: true

Warning[:deprecated] = false

ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../Gemfile', __dir__)

require 'bundler/setup' # Set up gems listed in the Gemfile.

require 'rubydns'

IN = Resolv::DNS::Resource::IN

INTERFACES = [
  [:udp, '0.0.0.0', 53],
  [:tcp, '0.0.0.0', 53],
].freeze

RubyDNS.run_server INTERFACES do
  match 'foo.dyn.crypto-libertarian.com', IN::A do |transaction|
    transaction.respond! '127.0.0.1'
  end

  otherwise do
    transaction.fail! :NXDomain
  end
end
