#!/usr/bin/env ruby
# frozen_string_literal: true

Warning[:deprecated] = false

ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../Gemfile', __dir__)

require 'bundler/setup' # Set up gems listed in the Gemfile.

require 'rubydns'

IN = Resolv::DNS::Resource::IN

INTERFACES = [
  [:udp, '0.0.0.0', 53],
  [:tcp, '0.0.0.0', 53],
].freeze

RubyDNS.run_server INTERFACES do
  match(/\A([^.]+)\.dyn\.crypto-libertarian\.com\z/, IN::A) do |tx, m|
    redis = Redis.new url: ENV['REDIS_URL']

    domain = "#{m[1]}.dyn.crypto-libertarian.com"

    ip = redis.hget('ips', domain).to_s.strip.freeze
    ip = nil if ip.empty?

    if ip.nil?
      tx.fail! :NXDomain
    else
      tx.respond! ip
    end
  end

  otherwise do |tx|
    tx.fail! :NXDomain
  end
end
