---
- include_tasks: nginx.yml
- meta: flush_handlers

- name: Add Yarn APT key
  apt_key:
    id: '72ECF46A56B4AD39C907BBB71646B01B86E50310'
    url: 'https://dl.yarnpkg.com/debian/pubkey.gpg'

- name: Add Yarn APT repository
  apt_repository:
    filename: 'yarn'
    repo: 'deb https://dl.yarnpkg.com/debian/ stable main'

- name: Install system packages for FediHub Website
  apt:
    update_cache: true
    name:
      - libpq-dev
      - libpq5
      - yarn
  notify: Load, enable and restart FediHub Website

- name: Create FediHub Website system group
  group:
    name: '{{ fedihub__website__group }}'
    system: true
  notify: Load, enable and restart FediHub Website

- name: Create FediHub Website system user
  user:
    name: '{{ fedihub__website__user }}'
    group: '{{ fedihub__website__group }}'
    system: true
    create_home: true
  notify: Load, enable and restart FediHub Website

- name: Install rustup
  become_user: '{{ fedihub__website__user }}'
  shell:
    cmd: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly"
    creates: '/home/fedihub-website/.cargo/bin/rustup'
  notify: Load, enable and restart FediHub Website

- name: Create FediHub Website directories
  file:
    state: directory
    path: '{{ fedihub__website__opt_dir }}'
    mode: 'u=rwx,g=rwx,o=rx'
    owner: '{{ fedihub__website__user }}'
    group: '{{ fedihub__website__group }}'
  notify: Load, enable and restart FediHub Website

- name: Get FediHub Website source code
  become_user: '{{ fedihub__website__user }}'
  git:
    repo: 'https://github.com/fedihubcom/website.git'
    dest: '{{ fedihub__website__src_dir }}'
    version: 'a263fe85d6a0b279dc759a41da8670cdda6b3dc5'
  notify: Load, enable and restart FediHub Website

- name: Build FediHub Website source code
  become_user: '{{ fedihub__website__user }}'
  shell:
    cmd: '/home/fedihub-website/.cargo/bin/cargo build --release'
    chdir: '{{ fedihub__website__src_dir }}'
    creates: '{{ fedihub__website__bin_path }}'
  notify: Load, enable and restart FediHub Website

- name: Install FediHub Website asset dependencies
  become_user: '{{ fedihub__website__user }}'
  shell:
    cmd: 'yarn install'
    chdir: '{{ fedihub__website__src_dir }}'
  register: yarn_install_result
  changed_when: "'Already up-to-date.' not in yarn_install_result.stdout"
  notify: Load, enable and restart FediHub Website

- name: Build FediHub Website assets
  become_user: '{{ fedihub__website__user }}'
  shell:
    cmd: 'yarn build'
    chdir: '{{ fedihub__website__src_dir }}'
    creates: '{{ fedihub__website__src_dir }}/public/assets/bundle.css'
  notify: Load, enable and restart FediHub Website

- name: Specify FediHub Website environment
  template:
    src: '../templates/env'
    dest: '{{ fedihub__website__src_dir }}/.env'
    mode: 'u=rw,g=,o='
    owner: '{{ fedihub__website__user }}'
    group: '{{ fedihub__website__group }}'
  notify: Load, enable and restart FediHub Website

- name: Create FediHub Website systemd service
  template:
    src: '../templates/fedihub-website.service'
    dest: '{{ fedihub__website__service_file }}'
    mode: 'u=rw,g=rw,o=r'
    owner: root
    group: root
  notify: Load, enable and restart FediHub Website

- name: Install Diesel CLI
  become_user: '{{ fedihub__website__user }}'
  shell:
    cmd: '/home/fedihub-website/.cargo/bin/cargo install diesel_cli  --no-default-features --features postgres'
    chdir: '{{ fedihub__website__src_dir }}'
    creates: '/home/fedihub-website/.cargo/bin/diesel'

- name: Migrate database
  become_user: '{{ fedihub__website__user }}'
  shell:
    cmd: '/home/fedihub-website/.cargo/bin/diesel migration run --locked-schema'
    chdir: '{{ fedihub__website__src_dir }}'
  register: diesel_migration_run_result
  changed_when: "diesel_migration_run_result.stdout != ''"
