---
- hosts: git.crypto-libertarian.com
  module_defaults:
    apt:
      force_apt_get: true
      update_cache: true
      cache_valid_time: 86400
  roles:
    - kotovalexarian.common
  tasks:
    - name: Install system packages
      apt:
        name: cgit
