---
- hosts: misc.crypto-libertarian.com
  module_defaults:
    apt:
      force_apt_get: true
      update_cache: true
      cache_valid_time: 86400
  roles:
    - kotovalexarian.common
    - rvm.ruby
  tasks:
    - name: Install system packages
      apt:
        name: redis-server

    - name: Create system group
      group:
        name: report_ip
        system: true

    - name: Create system user
      user:
        name: report_ip
        group: report_ip
        system: true
        create_home: false

    - name: Check RVM gemset
      shell: /bin/bash --login -c 'rvm use ruby-2.7.0@report_ip'
      ignore_errors: true
      register: check_rvm_gemset_result
      changed_when: false

    - name: Create RVM gemset
      shell: /bin/bash --login -c 'rvm use ruby-2.7.0@report_ip --create'
      when: check_rvm_gemset_result.rc != 0

    - name: Check Bundler
      shell: >
        /bin/bash --login -c
        "rvm ruby-2.7.0@report_ip do
        gem info bundler --installed --version '~> 2.0'"
      ignore_errors: true
      register: check_bundler_result
      changed_when: false

    - name: Install Bundler
      shell: >
        /bin/bash --login -c
        "rvm ruby-2.7.0@report_ip do
        gem install bundler -v '~> 2.0'"
      when: check_bundler_result.rc != 0

    - name: Copy application
      copy:
        src: ../../apps/report_ip/
        dest: /opt/report_ip/
        owner: report_ip
        group: report_ip

    - name: Install gems
      shell: >
        /bin/bash --login -c
        "rvm ruby-2.7.0@report_ip do
        bundle install --gemfile /opt/report_ip/Gemfile"
      changed_when: false

    - name: Install systemd service
      copy:
        src: ../../files/report_ip.service
        dest: /etc/systemd/system/report_ip.service
        owner: root
        group: root
        mode: 'u=rw,g=r,o=r'
      register: install_systemd_service_resule

    - name: Update systemd service
      systemd:
        daemon_reload: true
        name: report_ip.service
        enabled: true
      when: install_systemd_service_resule.changed

    - name: Restart systemd service
      systemd:
        name: report_ip.service
        state: restarted
      changed_when: false
