---
- hosts: misc.crypto-libertarian.com
  module_defaults:
    apt:
      force_apt_get: true
      update_cache: true
      cache_valid_time: 86400
  roles:
    - kotovalexarian.common
    - rvm.ruby
  tasks:
    - name: Check RVM gemset
      shell: /bin/bash --login -c 'rvm use ruby-2.7.0@report_ip'
      ignore_errors: true
      register: check_rvm_gemset_result
      changed_when: false

    - name: Create RVM gemset
      shell: /bin/bash --login -c 'rvm use ruby-2.7.0@report_ip --create'
      when: check_rvm_gemset_result.rc != 0

    - name: Check Bundler
      shell: >
        /bin/bash --login -c
        "rvm ruby-2.7.0@report_ip do
        gem info bundler --installed --version '~> 2.0'"
      ignore_errors: true
      register: check_bundler_result
      changed_when: false

    - name: Install Bundler
      shell: >
        /bin/bash --login -c
        "rvm ruby-2.7.0@report_ip do
        gem install bundler -v '~> 2.0'"
      when: check_bundler_result.rc != 0
