---
- hosts: misc.crypto-libertarian.com
  module_defaults:
    apt:
      force_apt_get: true
      update_cache: true
      cache_valid_time: 86400
  roles:
    - kotovalexarian.common
  tasks:
    - name: Create directory for publications
      file:
        state: directory
        path: /var/www/pub
        owner: root
        group: root
        mode: 'u=rwx,g=rx,o=rx'
