---
- hosts: postgres
  module_defaults:
    apt:
      force_apt_get: true
      update_cache: true
      cache_valid_time: 86400
  roles:
    - kotovalexarian.common
    - geerlingguy.postgresql
  tasks:
    - name: Create daily Cron job for PostgreSQL backup
      template:
        src: ../../templates/pg_backup
        dest: /etc/cron.daily/pg_backup
        mode: 'u=rwx,g=rx,o=rx'
        owner: root
        group: root
