---
- hosts: postgres.crypto-libertarian.com
  module_defaults:
    apt:
      force_apt_get: true
      update_cache: true
      cache_valid_time: 86400
  roles:
    - kotovalexarian.common
    - geerlingguy.postgresql
  tasks:
    - name: Create weekly Cron job for PostgreSQL backup
      copy:
        src: ../../files/pg_backup
        dest: /etc/cron.weekly/pg_backup
        mode: 'u=rwx,g=rx,o=rx'
        owner: root
        group: root
