---
- hosts: raspberrypi
  module_defaults:
    apt:
      force_apt_get: true
      update_cache: true
      cache_valid_time: 86400
  roles:
    - kotovalexarian.common
  tasks:
    - name: Install cron jon "report_ip"
      template:
        src: ../../templates/report_ip
        dest: /etc/cron.d/report_ip
        owner: root
        group: root
        mode: 'u=rw,g=r,o='
