---
- name: Restart Nginx
  systemd:
    name: nginx
    state: restarted

- name: Load, enable and restart Matrix Media Repo
  systemd:
    name: '{{ matrix_media_repo__service }}'
    daemon_reload: true
    enabled: true
    state: restarted
