---
postgres__hba:
  - type: local
    database: all
    user: postgres
    method: peer

  - type: local
    database: all
    user: all
    method: peer

  - type: host
    database: all
    user: all
    address: '127.0.0.1/32'
    method: md5

  - type: host
    database: all
    user: all
    address: '::1/128'
    method: md5

  - type: local
    database: replication
    user: all
    method: peer

  - type: host
    database: replication
    user: all
    address: '127.0.0.1/32'
    method: md5

  - type: host
    database: replication
    user: all
    address: '::1/128'
    method: md5

postgres__config:
  - key: listen_addresses
    value: '*'
