---
- hosts: all
  tasks:
    - name: APT update & upgrade
      become: true
      apt:
        update_cache: true
        upgrade: safe
    - name: Install useful packages
      become: true
      apt:
        state: present
        name: ['bash-completion', 'colordiff', 'curl', 'less', 'vim']
    - name: Harden SSH daemon
      become: true
      lineinfile:
        state: present
        path: /etc/ssh/sshd_config
        regexp: '{{ item.regexp }}'
        line: '{{ item.line }}'
      with_items:
        - regexp: '^#?PermitRootLogin '
          line:   'PermitRootLogin no'
        - regexp: '^#?MaxAuthTries '
          line:   'MaxAuthTries 2'
        - regexp: '^#?MaxSessions '
          line:   'MaxSessions 5'
        - regexp: '^#?PasswordAuthentication '
          line:   'PasswordAuthentication no'
        - regexp: '^#?ChallengeResponseAuthentication '
          line:   'ChallengeResponseAuthentication no'
        - regexp: '^#?AllowAgentForwarding '
          line:   'AllowAgentForwarding no'
        - regexp: '^#?AllowTcpForwarding '
          line:   'AllowTcpForwarding no'
        - regexp: '^#?X11Forwarding '
          line:   'X11Forwarding no'
        - regexp: '^#?TCPKeepAlive '
          line:   'TCPKeepAlive no'
        - regexp: '^#?UseDNS '
          line:   'UseDNS no'
    - name: Restart SSH daemon
      become: true
      systemd:
        daemon_reload: true
        name: sshd
        state: restarted
